### ISSUE TITLE
Performance tuning

### ISSUE THREAD

**Issue by Sataniel98** [DRE2N/DungeonsXL#39]
- [x] Copy files asynchronously
- [x] Load worlds asynchronously
- [x] Copy default raw world instead of generating a new one
- [ ] Check all Collections and decide which implementation to use
- [x] Debug expensive methods
- [x] Testing
